### ISSUE TITLE
!!!

### ISSUE THREAD

**Issue by worthant** [Imtjl/fp-red-black-tree-dict-lab2#1]
## TODO

- [x] Разобраться нормально с:
  - [x] свёртки
    - [x] отличие свёрток справа и слева?
  - [x] фильтрация
  - [x] слияние моей структуры, подумать как сделать так, чтоб слияние было идемпотентным (**моноид**)
  - [x] алгоритмы вставки, удаления и поиска в LLRB tree

- [x] Написать самому с нуля PBT для моей структуры, потыкаться для начала ручками посмотреть как она отрабатывает, начинать с маленьких выборок, изучить фреймворк для тестирования
